### ISSUE TITLE
Generate CIFF v1 exports

### ISSUE THREAD

**Issue by lintool** [osirrc/ciff#10]
Generate "official" CIFF v1 exports of Robust04 and cw12b. Any other indexes people want?

**Comment by Chriskamphuis** [comment]
core17 and core18, but I am also fine with generating it myself?

**Comment by lintool** [comment]
nah, let me generate all of them together...

**Comment by JMMackenzie** [comment]
Could always add gov2 and CW09B as well, but perhaps we can stick to the smaller collections for now + CW12B?

**Comment by lintool** [comment]
I've generated Robust04 and CW12b for our arxiv paper. Let's generate more as needed.
