### ISSUE TITLE
Add new per-doc integrity check for CIFF

### ISSUE THREAD

**Issue by lintool** [osirrc/ciff#23]
Extracted from #22 

@cmacdonald suggested:

> are the sums of the tfs in the posting lists for each document equals to the document lengths for the corresponding documents (expensive in memory)

I punted on that in the CR. We might want to come back and add this.

**Comment by cmacdonald** [comment]
On reflection, I think that its unlikely for the sum of the tfs in the posting lists to be equal to total_terms_in_collection, but for the individual document lengths not to match.  Suggest not needed.

**Comment by lintool** [comment]
Okay, less code to write!
