### ISSUE TITLE
give links to implementations in README

### ISSUE THREAD

**Issue by cmacdonald** [osirrc/ciff#3]

**Comment by lintool** [comment]
Hey @cmacdonald - my idea is that everyone would simply put their implementation here, in this repo - so we have Java/C++/etc., exporters to all the systems all in one place...

**Comment by cmacdonald** [comment]
If we put them all in one repo, then we can't do any kind of GitHub/Travis CI on them.

Also, Terrier has maven integration, to which I'm going to add Jitpack as a repo target in the next release. That should mean that CIFF files can be ingested without installing any software, using simply:

```
terrier -P com.github:terrier-ciff ciff-ingest [filenames]
```

**Comment by lintool** [comment]
I see. I've added you as a collaborator to this repo, you should be able to add to the README directly when you set everything up.

**Comment by lintool** [comment]
The downside of this approach, I believe, is that you'll need to duplicate the protobuf definition... or we need to publish a Maven `ciff` artifact that Terrier pulls. But I assume you don't want all the Lucene stuff transitively pulled in... so we'll really need something like `ciff-core` and `ciff-lucene-exporter`... at which point I think we're over-engineering this...

**Comment by cmacdonald** [comment]
if ciff definition changes, code will likely have to change as well, so I am happy copying it over.

**Comment by JMMackenzie** [comment]
@arjenpdevries @Chriskamphuis @cmacdonald @andrewtrotman 

I updated the README with a pointer to the relevant PISA repo. Perhaps you could all follow suit, and then we can close this off. For reference, our ingester page is here: https://github.com/pisa-engine/common-index-format 

You may wish to use a similar description in your README

**Comment by lintool** [comment]
@JMMackenzie rename `common-index-file-format` or `ciff` to be consistent?

**Comment by JMMackenzie** [comment]
> @JMMackenzie rename `common-index-file-format` or `ciff` to be consistent?
Fix in #7

**Comment by lintool** [comment]
@andrewtrotman @Chriskamphuis @cmacdonald add links to your importers in the README?

**Comment by cmacdonald** [comment]
think we can close this issue now.
